name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Laravel Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64 -t your-registry/laravel-image -f path/to/laravel/Dockerfile .
        docker push your-registry/laravel-image

    - name: Build and Push Angular Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64 -t your-registry/angular-image -f path/to/angular/Dockerfile .
        docker push your-registry/angular-image

    - name: Set up kubectl
      uses: steebchen/kubectl@v1
      with:
      kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f path/to/laravel-deployment.yaml
          kubectl apply -f path/to/angular-deployment.yaml    